# /etc/apache2/sites-available/hospital.conf
# Sitio del Hospital Privado Castillejos: http://www.hospital.redes.test

<VirtualHost *:80>
    ServerName  www.hospital.redes.test
    ServerAdmin admin@hospital.redes.test
    DocumentRoot /var/www/hospital

    <Directory /var/www/hospital>
        Options -Indexes +FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    ErrorLog  ${APACHE_LOG_DIR}/hospital-error.log
    CustomLog ${APACHE_LOG_DIR}/hospital-access.log combined
</VirtualHost>
